# Generated by Django 3.1.6 on 2021-07-31 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_name', models.CharField(max_length=255)),
                ('data', models.CharField(max_length=500)),
                ('time', models.TimeField()),
                ('image', models.ImageField(upload_to='')),
                ('location', models.CharField(max_length=255)),
                ('is_liked', models.BooleanField(default=False)),
            ],
        ),
    ]
